# Generated by Django 3.2.16 on 2022-12-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_project_artifact_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='model_mapping_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_mapping_group', to='core.settingsgroup'),
        ),
    ]
