# Generated by Django 3.2.16 on 2023-01-10 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20230110_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='group',
            field=models.ForeignKey(blank=True, limit_choices_to={'type__key__exact': 'Group Type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_group', to='core.setting'),
        ),
    ]
