# Generated by Django 3.2.16 on 2023-01-10 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_setting_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='artifact_group',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__key__exact': 'Artifact Groups'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifact_group', to='core.setting'),
        ),
    ]
