# Generated by Django 3.2.16 on 2023-01-10 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_project_artifact_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='artifact_group',
        ),
        migrations.RemoveField(
            model_name='project',
            name='model_mapping_group',
        ),
        migrations.RemoveField(
            model_name='project',
            name='model_predictions_group',
        ),
        migrations.RemoveField(
            model_name='project',
            name='model_source_type_mapping_group',
        ),
        migrations.AddField(
            model_name='project',
            name='artifacts_group',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__key__exact': 'Artifact Groups'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts_group', to='core.setting'),
        ),
        migrations.AddField(
            model_name='project',
            name='files_to_models_group',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__key__exact': 'File to Model Groups'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_to_models_group', to='core.setting'),
        ),
        migrations.AddField(
            model_name='project',
            name='models_group',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__key__exact': 'Model Groups'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models_group', to='core.setting'),
        ),
        migrations.AddField(
            model_name='project',
            name='predictions_group',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__key__exact': 'Prediction Groups'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions_group', to='core.setting'),
        ),
    ]
