# Generated by Django 3.2.16 on 2023-01-13 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_setting_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='type',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_type': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_type', to='core.setting'),
        ),
    ]
