# Generated by Django 3.2.16 on 2023-01-13 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_setting_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ('key',)},
        ),
        migrations.AlterField(
            model_name='setting',
            name='group',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('type__key__exact', 'Group Type'), ('type__key__exact', 'Group'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_group', to='core.setting'),
        ),
    ]
