# Generated by Django 3.2.16 on 2023-01-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20230113_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='models_group',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__key__exact': 'Evaluation Model Groups'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models_group', to='core.setting'),
        ),
    ]
